global:
  qsname: quickstart-ibm-websphere-liberty
  owner: susarlam@amazon.com
  # Regions
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
    - eu-central-1
    - eu-west-1
    - ap-southeast-2    
  reporting: true
  
tests:
  quickstart-ibm-websphere-liberty:
    parameter_input: liberty-master.json
    template_file: liberty-master.template
    regions:
    - ca-central-1
